{{- if and .Values.search.enabled (or .Values.api.enabled .Values.worker.enabled) }}
{{- $s := include "forge.search" . | fromJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forge.fullname" . }}-shared-search-secret
  labels:
{{- include "forge.labels" . | nindent 4 }}
type: Opaque
data:
  SEARCH_PASSWORD: {{ $s.password | default "" | b64enc | quote }}
{{- end }}
