{{- if or .Values.api.enabled .Values.edge.enabled .Values.worker.enabled .Values.scheduler.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forge.fullname" . }}-shared-redis-secret
  labels:
{{- include "forge.labels" . | nindent 4 }}
type: Opaque
data:
  CACHE_PASSWORD: {{ include "forge.cache.password" . | b64enc | quote }}
{{- end }}
