{{- if and .Values.mail.enabled (or .Values.api.enabled .Values.worker.enabled .Values.scheduler.enabled) }}
{{- $m := include "forge.mail" . | fromJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forge.fullname" . }}-shared-mail-secret
  labels:
{{- include "forge.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq $m.type "smtp" }}
  EMAIL_PASSWORD: {{ $m.password | default "" | b64enc | quote }}
  EMAIL_API_KEY: {{ "" | b64enc | quote }}
  {{- else if eq $m.type "sendgrid" }}
  EMAIL_API_KEY: {{ $m.apiKey | default "" | b64enc | quote }}
  EMAIL_PASSWORD: {{ "" | b64enc | quote }}
  {{- else }}
  EMAIL_ACCESS_KEY: {{ $m.accessKey | default "" | b64enc | quote }}
  EMAIL_SECRET_KEY: {{ $m.secretKey | default "" | b64enc | quote }}
  {{- end }}
{{- end }}
