{{- if .Values.scheduler.enabled }}
{{- $db := include "forge.datasource" . | fromJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forge.fullname" . }}-scheduler-secret
  labels:
{{- include "forge.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ $db.password | b64enc | quote }}
  FORGE_FIELD_ENCRYPTION_KEY: {{ .Values.secret.masterKek | b64enc | quote }}
{{- end }}
